
# server settings
spring:
  application:
    name: api-gateway

# gateway settings
  cloud:
    gateway:
      routes:
        - id: user-service
          uri:
            http://localhost:8082/
          predicates:
            - Path= /user/**
        - id: note-service
          uri:
            http://localhost:8083/
          predicates:
            - Path= /note/**
# Eureka settings
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

